### PR TITLE
UX changes for undesirable behaviors and remove top level "All assertions are met" radio option

### PR DESCRIPTION
**Pull request by spectranaut**
[Preview Tests](https://raw.githack.com/w3c/aria-at/fix-undesirable-validation/index.html)

[Example test](https://raw.githack.com/w3c/aria-at/fix-undesirable-validation/tests/checkbox/test-04-navigate-to-checked-checkbox-reading.html?at=jaws)

To test validation:
1. Select "yes there are undesirable behaviors" for any command for any tests
2. Click the "submit results" button at the bottom of the page
3. You should see "required" by the "undesirable results" fieldset legend for the command in step (1)
4. Select "other"
2. Click the "submit results" button at the bottom of the page
3. You should see "required" by the "undesirable results" for the "other" input for the command

To test tab stop changes:
1. Select "yes there are undesirable changes"
2. Tab into the undesirable checkbox list
3. A second tab should move you out of the the undesirable checkbox list
4. Shift-tab back in
5. Use the arrow keys to move between the undesirable checkboxes
6. Tab out and tab back, the last checkbox with focus should be in the tab sequence

### CODE REVIEW

**Comment by evmiguel** [comment]
@spectranaut when I click, "Yes, there are undesirable behaviors", only the "Other" field is enabled. Is that what is supposed to happen?

https://www.loom.com/share/7c04a7821e57465f840ef70295c71916

**Comment by spectranaut** [comment]
@evmiguel I fixed the bug! Can you do another review? Thanks :)

**Comment by spectranaut** [comment]
This PR now has the updates requested in https://github.com/w3c/aria-at/issues/320

**Comment by rmeritz** [comment]
@spectranaut - Everything worked as described in the new tab behavior except maybe "A second tab should move you out of the undesirable checkbox list". This moved me to the "If other selected please explain:" textbox. I wasn't sure if it was supposed to move me their I kind of assumed according to the instructions I should have moved to the next SR output box instead.

**Comment by spectranaut** [comment]
@rmeritz sorry what you identified is the correct behavior, it moves you out of the checkboxes and into the "other" box. I wasn't sure if this was the exact correct behavior but it is intentional and we can wait until feedback to change it if users don't like this behavior.

**Pull request merged**
