### PR TITLE
Create updated tests for APG design pattern example: Toggle Button

### LINKED ISSUE #396: Create updated tests for APG design pattern example: Toggle Button
Below is the test plan for the toggle button example.  Each test title is marked up as a level 4 heading to facilitate screen reader navigation.

#### Navigate forwards to a not pressed toggle button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Modes: reading, interaction
* Instructions:
    * Reading mode: With the reading cursor on the 'Navigate forwards from here' link, navigate to the 'Mute' button.
    * Interaction mode: With focus on the 'Navigate forwards from here' link, navigate to the 'Mute' button.
* Setup script description: sets focus on a link before the button

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|reading|<ul><li>Down Arrow</li><li>B</li><li>F</li><li>Tab</li></ul>|
|JAWS, NVDA|interaction|Tab|
|macOS VoiceOver|interaction|<ul><li>Control+Option+Right Arrow</li><li>Tab</li><li>Control+Option+Command+J</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Role 'button' is conveyed|required|
|Name 'Mute' is conveyed|required|
|State 'not pressed' is conveyed|required|

##### References

`button, aria-pressed	`

#### Navigate backwards to a not pressed toggle button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Modes: reading, interaction
* Instructions:
    * Reading mode: With the reading cursor on the 'Navigate backwards from here' link, navigate to the 'Mute' button.
    * Interaction mode: With focus on the 'Navigate backwards from here' link, navigate to the 'Mute' button.
* Setup script description: sets focus on a link after the button

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|reading|<ul><li>Up Arrow</li><li>Shift+B</li><li>Shift+F</li><li>Shift+Tab</li></ul>|
|JAWS, NVDA|interaction|Shift+Tab|
|macOS VoiceOver|interaction|<ul><li>Control+Option+Left Arrow</li><li>Shift+Tab</li><li>Shift+Control+Option+Command+J</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Role 'button' is conveyed|required|
|Name 'Mute' is conveyed|required|
|State 'not pressed' is conveyed|required|

##### References

`button, aria-pressed	`

#### Navigate forwards to a pressed toggle button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Modes: reading, interaction
* Instructions:
    * Reading mode: With the reading cursor on the 'Navigate forwards from here' link, navigate to the 'Mute' button.
    * Interaction mode: With focus on the 'Navigate forwards from here' link, navigate to the 'Mute' button.
* Setup script description: sets focus on a link before the button, and sets the state of the button to 'pressed'

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|reading|<ul><li>Down Arrow</li><li>B</li><li>F</li><li>Tab</li></ul>|
|JAWS, NVDA|interaction|Tab|
|macOS VoiceOver|interaction|<ul><li>Control+Option+Right Arrow</li><li>Tab</li><li>Control+Option+Command+J</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Role 'button' is conveyed|required|
|Name 'Mute' is conveyed|required|
|State 'pressed' is conveyed|required|

##### References

`button, aria-pressed	`

#### Navigate backwards to a pressed toggle button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Modes: reading, interaction
* Instructions:
    * Reading mode: With the reading cursor on the 'Navigate backwards from here' link, navigate to the 'Mute' button.
    * Interaction mode: With focus on the 'Navigate backwards from here' link, navigate to the 'Mute' button.
* Setup script description: sets focus on a link after the button, and sets the state of the button to 'pressed'

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|reading|<ul><li>Up Arrow</li><li>Shift+B</li><li>Shift+F</li><li>Shift+Tab</li></ul>|
|JAWS, NVDA|interaction|Shift+Tab|
|macOS VoiceOver|interaction|<ul><li>Control+Option+Left Arrow</li><li>Shift+Tab</li><li>Shift+Control+Option+Command+J</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Role 'button' is conveyed|required|
|Name 'Mute' is conveyed|required|
|State 'pressed' is conveyed|required|

##### References

`button, aria-pressed	`

#### Read information about a not pressed toggle button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Modes: reading, interaction
* Instructions:
    * Reading mode: With the reading cursor on the 'Mute' button, read information about the button.
    * Interaction mode: With focus on the 'Mute' button, read information about the button.
* Setup script description: sets focus on the button

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|reading, interaction|<ul><li>Insert+Tab</li><li>Insert+Up</li></ul>|
|macOS VoiceOver|interaction|<ul><li>Control+Option+F3</li><li>Control+option+F4</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Role 'button' is conveyed|required|
|Name 'Mute' is conveyed|required|
|State 'not pressed' is conveyed|required|

##### References

`button, aria-pressed	`

#### Read information about a pressed toggle button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Modes: reading, interaction
* Instructions:
    * Reading mode: With the reading cursor on the 'Mute' button, read information about the button.
    * Interaction mode: With focus on the 'Mute' button, read information about the button.
* Setup script description: sets focus on the button, and sets its state to 'pressed'

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|reading, interaction|<ul><li>Insert+Tab</li><li>Insert+Up</li></ul>|
|macOS VoiceOver|interaction|<ul><li>Control+Option+F3</li><li>Control+option+F4</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Role 'button' is conveyed|required|
|Name 'Mute' is conveyed|required|
|State 'pressed' is conveyed|required|

##### References

`button, aria-pressed	`

#### Operate a not pressed toggle button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Modes: reading, interaction
* Instructions:
    * Reading mode: With the reading cursor on the 'Mute' button, activate the button.
    * Interaction mode: With focus on the 'Mute' button, activate the button.
* Setup script description: sets focus on the button

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|reading, interaction|<ul><li>Space</li><li>Enter</li></ul>|
|macOS VoiceOver|interaction|<ul><li>Control+Option+Space</li><li>Space</li><li>Enter</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Change in state, to 'pressed', is conveyed|required|

##### References

`button, aria-pressed	`

#### Operate a pressed toggle button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Modes: reading, interaction
* Instructions:
    * Reading mode: With the reading cursor on the 'Mute' button, activate the button.
    * Interaction mode: With focus on the 'Mute' button, activate the button.
* Setup script description: sets focus on the button, and sets its state to 'pressed'

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|interaction|<ul><li>Space</li><li>Enter</li></ul>|
|macOS VoiceOver|interaction|<ul><li>Control+Option+Space</li><li>Space</li><li>Enter</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Change in state, to 'not pressed', is conveyed|required|

##### References

`button, aria-pressed	`

### PR DESCRIPTION
**Pull request by IsaDC**
[Preview Tests](https://raw.githack.com/w3c/aria-at/tests/toggle-button/build/index.html)

Resolves #396.

### CODE REVIEW

**Comment by jscholes** [comment]
@IsaDC Please review and remove draft status when you're happy with it.  I can't formally request a review from the PR author 🤦‍♂️

**Comment by jscholes** [comment]
@IsaDC I fixed the backslashes in `references.csv`, and re-marked this as draft.  Please review the test page functionality and setup scripts.

**Comment by jscholes** [comment]
@zcorpan Thanks for the feedback, we'll get it addressed.  The community group recommendation is to provide standard comments on the PR referencing test numbers manually, rather than line-by-line comments on the diff.  They are far easier to read with a screen reader, particularly given that CSV records are long and the individual problem just ends up buried somewhere within one.  If you could follow that in future, that would be great 👍

**Comment by jscholes** [comment]
@IsaDC When INS_TAB is fixed, please review the setup script functionality and then mark as ready to review.

**Comment by zcorpan** [comment]
@jscholes noted, thanks!

**Pull request merged**
