### PR TITLE
Provide unique table cell text on review page

### PR DESCRIPTION
**Pull request by howard-e**
[Preview Tests](https://raw.githack.com/w3c/aria-at/bocoup/fix-issue-599/build/index.html)

Address #599.

Also related to #598 and https://github.com/w3c/aria-at/pull/611.

### CODE REVIEW

**Review by mzgoddard — APPROVED** [review]
Looks good to me.

**Review by alflennik — COMMENTED** [review]
It seems to me that adding the `th` might be enough to solve the problem fixed with the aria-labels, so perhaps the aria-labels aren't needed. @jscholes feel free to weigh in?

**Comment by jscholes** [comment]
@alflennik There are situations where table headers won't be conveyed alongside the link.  For instance, when using the links list in a screen reader (e.g. NVDA+F7, JAWS+F7).  So the link text being unambiguous is also a good idea.  However, in the case of the commit links, the text is overly verbose, and the "Commit of Last Change:" prefix should be removed.

**Comment by jscholes** [comment]
@mcking65 I mostly recommend that the unique context be provided at the end of the existing control, and be separated by something which triggers a pause in screen reader speech.  So rather than "Actions where X", I would want "Actions: X", with a colon and a space.  This, in my view:

1. doesn't add too much cognitive overhead, because the information is easy to ignore given its position and separation; and
2. facilitates the use case of distinguishing between the controls with certain screen reader features, like the JAWS/NVDA+F7 elements list.

It also provides the maximum amount of flexibility, because table headers can be turned off, without losing context.  I don't think it's perfect, for a number of reasons, including the fact that row and column headers usually can't be turned off independently of each other.  But, it's what we have.

@howard-e Commit text is much better, thanks!

**Pull request merged**
