### PR TITLE
Refactor Navigation Menu Button test plan to V2 test format

### PR DESCRIPTION
**Pull request by IsaDC**
[Preview Tests](https://deploy-preview-996--aria-at.netlify.app)

### CODE REVIEW

**Comment by IsaDC** [comment]
@mcking65  this is ready for review.

**Review by mcking65 — CHANGES_REQUESTED** [review]
Link text in the references for example is incorrect:
It is "APG Example: Actions Menu Button Using"
It should be: "APG Example: Navigation Menu Button"

In test 1 and test 2, step 3 in the instructions has an extra comma:

>3. Starting at the 'Navigate forwards from here' link,, navigate to the menu button.


In the following tests, Change assertion priority to 3 for "convey role of the focused item, 'menu item':
Test 4: Open a menu
Test 5: Open a menu to the last item

In Test 9: Navigate to an item in a menu by typing a character, The VoiceOver command "w" needs to specify the setting for single character quick nav off.

**Comment by mcking65** [comment]
@IsaDC 

wow, I just realized that I was looking at the wrong test plan in preview! I was looking at action menu button. I'm relooking now.

**Comment by mcking65** [comment]
@IsaDC 

I revised my feedback after looking at the correct test plan ... it is very similar to what I previously posted.

**Comment by IsaDC** [comment]
@mcking65 I’ve implemented the required changes. Tests 7, 8, and 9 already had priority 3 for the menuitem.

**Review by mcking65 — APPROVED** [review]
thank you @IsaDC. I found two more minor inconsistencies and fixed them. Merging.

**Pull request merged**
