### PR TITLE
Create tests for APG design pattern example: Disclosure (Show/Hide) for Navigation Menus

### LINKED ISSUE #342: Create tests for APG design pattern example: Disclosure (Show/Hide) for Navigation Menus
#### Applies To

* APG design pattern: [Disclosure (Show/Hide)](https://w3c.github.io/aria-practices/#disclosure)
* Specific example: [Disclosure (Show/Hide) for Navigation Menus](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation.html)

#### Testing Notes

This issue thread will house all documentation relating to the development of a test plan for the "Disclosure (Show/Hide) for Navigation Menus" APG example, which conforms to the "Disclosure" design pattern.  All follow-ups (including the test plan itself) will be added as new comments to facilitate notifications, but this initial comment will be updated with relevant details and URLs as needed for convenience.

#### Useful Links

* [Previewable Tests Index](https://raw.githack.com/w3c/aria-at/tests/disclosure-navigation/tests/disclosure-navigation/index.html)
* [Previewable Tests Review Page](https://raw.githack.com/w3c/aria-at/tests/disclosure-navigation/review/disclosure-navigation.html)

#### Additional References

* [button (role)](https://w3c.github.io/aria/#button)
* [region(role)](https://w3c.github.io/aria/#region)
* [aria-label(property)](https://w3c.github.io/aria/#aria-label)
* [aria-current (state)](https://w3c.github.io/aria/#aria-current)
* [aria-expanded (state)](https://w3c.github.io/aria/#aria-expanded)

### PR DESCRIPTION
**Pull request by jscholes**
[Preview Tests](https://raw.githack.com/w3c/aria-at/tests/disclosure-navigation/build/index.html)

Resolves #342.

### CODE REVIEW

**Comment by jscholes** [comment]
@rmeritz, @spectranaut and others, the GitHub action doesn't seem to be running successfully for this PR.  It seems to fail when processing a task string, presumably in a commands.csv file, but it doesn't say which file or row.  Could you take a look?

**Comment by jscholes** [comment]
@rmeritz FYI, there was a trailing blank line at the end of `commands.csv` which was incorrectly being included, and the map for the command row only had a value (`\n`) for `testId`.  This is weird, because all other `commands.csv` files I've exported from Excel have a trailing blank line, but this one was treated differently by the script.

I've removed the last blank line from all CSVs new to this branch, and it seems to have worked.  But I had to add logging to `create-example-tests.js` to know which data it was trying to process, and which JSON file it was writing to.  It would be great if the script could be updated to:

* unambiguously output which test directory and file is currently being processed;
* log useful information such as the current JSON payload/object whenever there is an error of any kind (even if it isn't anticipated); and
* explicitly handle/ignore blank rows and notify of their existence.

**Review by IsaDC — APPROVED** [review]

**Comment by rmeritz** [comment]
@jscholes - Thanks for the feedback on potential improvements/pain points in the process. 

>  It would be great if the script could be updated to:
>  * unambiguously output which test directory and file is currently being processed;
>  * log useful information such as the current JSON payload/object whenever there is an error of any kind (even if it isn't anticipated); and
> * explicitly handle/ignore blank rows and notify of their existence.

I've created a ticket in our backlog to complete these improvements.

**Comment by jscholes** [comment]
Review note: the example in the reference directory isn't timestamped, because the script and pattern for this were added later than this PR (in https://github.com/w3c/aria-at/commit/4d77ba271c1caf15792252e560ff47a6b7fd4d05).  This can easily be fixed by merging master into this tests branch, adding the timestamped directory and then allowing the test pages to be regenerated.  But there are currently merge conflicts in files that haven't been manually touched during creation of this PR, such as the unrelated menubar editor tests.

**Pull request merged**
