### PR TITLE
Refactor Toggle Button test plan to V2 test format

### PR DESCRIPTION
**Pull request by IsaDC**
[Preview Tests](https://deploy-preview-993--aria-at.netlify.app)

### CODE REVIEW

**Comment by mcking65** [comment]
@howard-e 

Getting an ssl security error when trying to load the preview page. Is this the same problem we have in APG?

**Review by mcking65 — COMMENTED** [review]
@IsaDC,

This looks great!!

I have one recommendation based on our discussions of assertion priority definitions and to address the feedback from Apple.

Change priority from MUST to SHOULD for the assertion:

>State 'not pressed' is conveyed

For the following tests:
* Test 1: Navigate forwards to a not pressed toggle button
* Test 2: Navigate backwards to a not pressed toggle button
* Test 5: Request information about a not pressed toggle button

**Comment by mcking65** [comment]
@IsaDC 

I suggest deleting the log.txt and the 2 remaining v1 files.

**Comment by howard-e** [comment]
> @howard-e
> 
> Getting an ssl security error when trying to load the preview page. Is this the same problem we have in APG? [Preview Tests](https://deploy-preview-993--aria-at.netlify.app)

I get the same issue on Chrome (ERR_SSL_PROTOCOL_ERROR) and Firefox (SSL_ERROR_RX_RECORD_TOO_LONG). Safari loads fine.

I first noticed it this week and was hoping it was a Netlify issue that would sort itself out. There were a couple answers.netlify.com forum posts reporting the same where the issue eventually just "went away", but I'll have to spend some looking into it or getting some elevated help if it persists.

Luckily, the main website doesn't seem to be affected.

**Comment by IsaDC** [comment]
> @IsaDC,
> 
> This looks great!!
> 
> I have one recommendation based on our discussions of assertion priority definitions and to address the feedback from Apple.
> 
> Change priority from MUST to SHOULD for the assertion:
> 
> > State 'not pressed' is conveyed
> 
> For the following tests:
> 
> * Test 1: Navigate forwards to a not pressed toggle button
> * Test 2: Navigate backwards to a not pressed toggle button
> * Test 5: Request information about a not pressed toggle button

Done!

**Pull request merged**
