### PR TITLE
Revert "Make support.json the single source of truth for AT information"

### PR DESCRIPTION
**Pull request by zcorpan**
This reverts commit 0a88a6ceae079db866c561fbac26576519cca2f9.

See #175

### CODE REVIEW

**Comment by spectranaut** [comment]
I'm going to try to fix this today so we don't have to merge this PR!

**Comment by mfairchild365** [comment]
Thank you, @spectranaut! Apologies for not catching that exception sooner.

**Comment by spectranaut** [comment]
@mfairchild365 I think there wasn't actually a bug! I couldn't replicate one, even after talking to @zcorpan, so I'm closing this task.

I did, however, filed an issue about a change you made in the `applies_to` field: https://github.com/w3c/aria-at/issues/177 -- it's not blocking us but it should be addressed eventually! :)

**Comment by mfairchild365** [comment]
Phew! I'm glad it is working as expected. Thank you for raising the other issue.

**Pull request closed without merging**
