### PR TITLE
Fix for backslash separator in update-reference script output

### PR DESCRIPTION
**Pull request by howard-e**
[Preview Tests](https://raw.githack.com/w3c/aria-at/fix-422/build/index.html)

### CODE REVIEW

**Comment by jscholes** [comment]
@howard-e Thanks for working on this, but it doesn't really fix #422 exactly.  If somebody manually copies a Windows path into `references.csv`, which I do almost all the time, it still has to be modified because `references.csv` only accepts forward slashes.  This only fixes the case where someone is using the script output, which won't be 100% of the time.

Is it possible to make `references.csv` platform-agnostic in terms of separators?  This will reduce likely user error quite a bit.

**Comment by howard-e** [comment]
Thanks for the feedback @jscholes. I wasn't aware that was a case to be accounted for as #422 wasn't covering that particular scenario. But perhaps we could track that platform-agnostic approach for the processing of `references.csv` in a separate issue? I believe it may be significant enough for such.

**Comment by jscholes** [comment]
@howard-e The issue title is "Backslash doesn't work as separator in references.csv", although admittedly the body does talk more about the script.  So if we do go for a different issue, #422 will need to be renamed.

**Comment by howard-e** [comment]
Good point. How about we keep the issue open and expound on the description there?

**Review by jesdaigle — APPROVED** [review]

**Comment by s3ththompson** [comment]
@jscholes i renamed #422 (which will remain open after this PR is merged). would you mind reviewing this PR just as it applies to the normalizing the formatting of stdout for paths?

**Review by jscholes — APPROVED** [review]

**Comment by jscholes** [comment]
@s3ththompson Thanks, and approved.  I didn't realise this was blocking on me, apologies for that.

**Comment by s3ththompson** [comment]
@jscholes no problem, we hadn't explicitly added you as a reviewer until today, so it wasn't blocking on you. we'll make sure to explicitly request reviews going forward.

**Pull request merged**
