### PR TITLE
typo: double word 'the'

### PR DESCRIPTION
**Pull request by nschonni**
[Preview Tests](https://deploy-preview-595--aria-at.netlify.app)

### CODE REVIEW

**Review by howard-e — APPROVED** [review]

**Comment by nschonni** [comment]
@howard-e looks like that PR preview job is working now, but I don't think it's updating what you wanted it to

**Comment by howard-e** [comment]
> @howard-e looks like that PR preview job is working now, but I don't think it's updating what you wanted it to

Great! And do you mean the preview link? I'm seeing it now. Perhaps the bot was still building it

**Comment by nschonni** [comment]
Actually think it was a random GitHub glitch. When I refreshed the page a few times, it kept on flashing the edited open comment then reverting. Seeing it ok on this on and another 🎆

**Comment by s3ththompson** [comment]
@jscholes This is just a typo, but I wanted to cc you just in case since it affects the content of the test plans. We'll merge next week, unless we hear otherwise.

**Pull request merged**
