### PR TITLE
Update prototype test runner with new assertion priorities

### LINKED ISSUE #136: Fix the prototype runner for new assertion priorities
See https://github.com/w3c/aria-at/issues/117

### PR DESCRIPTION
**Pull request by zcorpan**
Fixes #136.

---

@spectranaut , please take a look. I don't know what I'm doing :-)

### CODE REVIEW

**Comment by zcorpan** [comment]
> Although, i just realized some tests have priority set to 3. Should that be changed in this PR?

This has been fixed in master already. I've rebased this.

Fixed `submitResults`.

I also found `scripts/test-reviewer.mjs` and fixed the priority strings there.

**Comment by zcorpan** [comment]
So the existing results tables are still using the 3 priorities. Maybe we can just edit the results JSON in this PR to change all priority 3 to priority 2.

**Comment by spectranaut** [comment]
Looks good and works, but there are still some tests with priority 3 in them!
```
~/w3c/aria-at/tests$ grep -r "\[3"
checkbox/navigate-out-of-checkbox-group-interaction.html:            [3, "Role 'group' is conveyed"],
checkbox/navigate-out-of-checkbox-group-interaction.html:            [3, "Group name 'Sandwich Condiments' is conveyed"],
checkbox/navigate-out-of-checkbox-group-interaction.html:            [3, "Boundaries of the group (before the first checkbox and after the last checkbox) are conveyed"]
checkbox/navigate-out-of-checkbox-group.html:            [3, "Role 'group' is conveyed"],
checkbox/navigate-out-of-checkbox-group.html:            [3, "Group name 'Sandwich Condiments' is conveyed"],
checkbox/navigate-out-of-checkbox-group.html:            [3, "Boundaries of the group (before the first checkbox and after the last checkbox) are conveyed"]
menubar-editor/read-menuitem-in-menubar-interaction.html:      [3, "The menubar label 'Text Formatting' is conveyed"]
menubar-editor/read-menuitem-in-menubar-reading.html:      [3, "The menubar label 'Text Formatting' is conveyed"]
```

**Comment by zcorpan** [comment]
I don't see them. I think the tests' priorities were fixed already on master. I've rebased on master and can merge.

**Pull request merged**
