### PR TITLE
Create tests for APG design pattern example: Actions Menu Button Example Using element.focus()

### LINKED ISSUE #357: Create tests for APG design pattern example: Actions Menu Button Example Using element.focus()
#### Applies To

* APG design pattern: [Menu Button](https://w3c.github.io/aria-practices/#menubutton)
* Specific example: [Actions Menu Button Example Using element.focus()](https://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions.html)

#### Testing Notes

This issue thread will house all documentation relating to the development of a test plan for the "Actions Menu Button Using element.focus()" APG example, which conforms to the "Menu Button" design pattern.  All follow-ups (including the test plan itself) will be added as new comments to facilitate notifications, but this initial comment will be updated with relevant details and URLs as needed for convenience.

#### Additional References

* [Menu (role)](https://w3c.github.io/aria/#menu)
* [Menuitem (role)](https://w3c.github.io/aria/#menuitem)
* [aria-haspopup (property)](https://w3c.github.io/aria/#aria-haspopup)
* [aria-controls (property)](https://w3c.github.io/aria/#aria-controls)
* [aria-labelledby (property)](https://w3c.github.io/aria/#aria-labelledby)
* [aria-expanded (state)](https://w3c.github.io/aria/#aria-expanded)

### PR DESCRIPTION
**Pull request by IsaDC**
[Preview Tests](https://raw.githack.com/w3c/aria-at/tests/menu-button-actions/build/index.html)

[Preview Tests](https://raw.githack.com/w3c/aria-at/tests/menu-button-actions/index.html)

Resolves #357

### CODE REVIEW

**Review by jongund — CHANGES_REQUESTED** [review]
Test 22 case for macOS is missing commands, in this case typing the "A" key.

Otherwise everything else looks good.

**Comment by jscholes** [comment]
@jongund Good catch, although the command is present in the CSV data.  I'll need to look into why it hasn't been picked up during compilation.

**Review by robfentress — CHANGES_REQUESTED** [review]
As with the active-descendent version of this pattern (#378), attempting to navigate to [VoiceOver for Mac](https://raw.githack.com/w3c/aria-at/tests/menu-button-actions/tests/menu-button-actions/test-22-naavigate-to-item-in-menu-by-typing-character-interaction.html?at=voiceover_macos) for **"Task ID 22, Navigate to an item in a menu by typing a character"**, takes me to a blank page.  I'm guessing this is somehow related to [Jon's feedback on Test 22](https://github.com/w3c/aria-at/pull/376#pullrequestreview-598875143).

**Comment by jscholes** [comment]
@robfentress, @jongund Both issues now fixed.

**Pull request merged**
