### PR TITLE
Update error message on "Unwanted U+FEFF" found in *.csv files

### PR DESCRIPTION
**Pull request by howard-e**
[Preview Tests](https://deploy-preview-1108--aria-at.netlify.app)

An error message was being thrown when running `npm run build` which read:

```
Unwanted U+FEFF found for key ﻿testId at index 0 while processing CSV.
Unwanted U+FEFF found for key ﻿assertionId at index 0 while processing CSV.
```

Found this to be coming from `tests/menu-button-actions-active-descendant/data/tests.csv` and `tests/menu-button-actions-active-descendant/data/assertions.csv`. This PR updates the message to add more detail and to remove the invisible character from both files:

```
[tests/menu-button-actions-active-descendant]: Unwanted U+FEFF found for key ﻿testId at index 0 while processing tests.csv.
[tests/menu-button-actions-active-descendant]: Unwanted U+FEFF found for key ﻿assertionId at index 0 while processing assertions.csv.
```

Seems this was introduced in #1092.

### CODE REVIEW

**Comment by IsaDC** [comment]
Thank you @howard-e 
That error confused me a few times.

**Comment by nschonni** [comment]
May want to update https://github.com/w3c/aria-at/blob/master/.gitattributes to opt everything into `eol=lf`

**Comment by howard-e** [comment]
@IsaDC said:

> Thank you @howard-e That error confused me a few times.

No problem! I also confirmed that this won't create a new version in the app because the test content hasn't actually changed so if all is well to you here, feel free to merge!

**Comment by howard-e** [comment]
> May want to update https://github.com/w3c/aria-at/blob/master/.gitattributes to opt everything into `eol=lf`

@nschonni certainly could! Could expand to include *.csv as well. Although the relation between `eol` and `u+feff` is lost on me here. Is there?

**Comment by nschonni** [comment]
You're right, it looks like there isn't anything native to git that will clean out the BOM. The `encoding` is set in `.editorconfig`, but I'm not sure how that would be enforced

**Review by stalgiag — APPROVED** [review]
Thanks for this! I needed to use the changes in this PR to make sense of the error I was seeing in the console in #1105 . I can confirm that these changes are helpful and necessary!

**Pull request merged**
