### PR TITLE
Generation of tests and review pages script improvements

### PR DESCRIPTION
**Pull request by howard-e**
[Preview Tests - from forked repository](https://raw.githack.com/howard-e/aria-at/develop/build/index.html)

* **NOTE: This is a duplicate of #441 which was merged but reverted due to lack of Windows support. Existing discussions may continue here.**
* **NOTE2: Would recommend filtering out \*.css, \*.html and \*.json files for the review to make it easier to navigate. Those are generated files which have been moved.**
* **NOTE3: See `docs/LOCAL_DEVELOPMENT.md` for information on new/updated script usages.**
  * Commands of note:
    * `npm run build` to update build folder with generated tests and review pages for all test plans
    * `npm run validate` to check if there are any validation errors for the test plans
    * `npm run build --testplan=<test_plan>`, eg. `npm run build --testplan=checkbox` to update build folder with a generated test and review page for a specific test plan
    * `npm run validate --validate=<test_plan>`, eg. `npm run validate --testplan=checkbox` to check if there are any validation errors for a specific test plan

This addresses a few issues identified with the automation/workflow scripts flow. See #384.

#### Test Plans generation script noisy output
When running `npm run create-all-tests` to generate test plans, many of the messages were unnecessary when one of the main goals was only understanding if anything unexpected had happened.

**Verbose Output**

An image of the verbose output the create-all-tests script was originally producing

The decision taken here was to completely silence the output except for displaying errors and providing a summary of how many tests have been generated.
A note on how many log lines have been suppressed along with instructions on how to view those messages is provided which means the original verbose output is now behind a `--verbose` flag.

**Non-Verbose Output**

Summarized non-verbose output of create-all-tests which show how much test plans were successfully processed, how many validation errors were found in other test plans as well as relevant messages covering that error and a help message indicating how to view this output in a verbose mode if wanted

#### Conflicts created by generated files from PR action + local development changes

* The generated output for the `npm run create-all-tests` and `npm run review-tests` will continue to work as normal. The only difference is that the files they generated are now stored in a `build` folder. This means means there will no longer be a chance for merge conflicts to occur on those in-line generated files when having to push/pull to/from the repository.
* These files are updated via a GitHub Action with `npm run build` which will then be referenced in the PR's `Preview Tests` link instead.
* This may also require persons pulling in the latest commit from the `base` branch (which the PR will also notify you of) before merging to avoid any possible merge conflicts but overall, the merge conflicts situation should be somewhat mitigated for the time being.

### CODE REVIEW

**Review by alflennik — APPROVED** [review]
I reran all the commands and looked over all changes since the last time I reviewed - nothing jumped out at me, besides perhaps the 40,862 lines changed. That is eye popping.

**Comment by jscholes** [comment]
@howard-e Can we work on a branch within this repo, please?  Working under your own account just means that it's more difficult for everybody else to checkout and contribute.

**Review by jscholes — APPROVED** [review]
@howard-e Thanks for your patience in waiting for my review here.  This is all working great 👍

**Comment by jscholes** [comment]
@jesdaigle / @s3ththompson Can we get a review on this PR soon?  I'd love to see it merged this week.

**Review by jesdaigle — APPROVED** [review]

**Pull request merged**
