### PR TITLE
Refactor Actions Menu Button Example Using element.focus() Test Plan to V2 Test Format

### PR DESCRIPTION
**Pull request by IsaDC**
[Preview Tests](https://deploy-preview-1122--aria-at.netlify.app)

* Preview [Action Menu Button Example Using element.focus() Test Plan | For Pattern: menu-button-actions](https://deploy-preview-1122--aria-at.netlify.app/review/menu-button-actions)
* [Preview of all Test plans](https://deploy-preview-1122--aria-at.netlify.app)

### CODE REVIEW

**Comment by IsaDC** [comment]
@mcking65  This Pull Request includes the feedback we discussed in today's CG meeting.

**Review by mcking65 — CHANGES_REQUESTED** [review]
The example reference points to the activedescendant example in APG instead of to the element.focus example.

In Test 9: Navigate to an item in a menu by typing a character, the VoiceOver command needs to specify that letter quick nav is off.

In the following tests, change priority to 3 for the assertion "convey role of the focused item, 'menu item'":
* Test 4: Open a menu
* Test 5: Open a menu to the last item

**Comment by IsaDC** [comment]
@mcking65  All done :)

**Comment by mcking65** [comment]
@IsaDC 

There's a bug in the setup script for tests 8. If you first run setup for test 7, the test 8 setup will set focus to the wrong item. If you refresh browser cache, the test 8 script will then work correctly and set focus to the first item.

To reproduce:
1. Open the test plan in Chrome.
2. Open the test 7 test window.
3. Run the setup script for test 7.
4. Close the test 7 window .
5. Open the test 8 test window.
6. Run the test 8 setup.

Expected behavior: Focus is set on action 1.

Actual behavior: Focus is set on action 4.

**Comment by IsaDC** [comment]
> @IsaDC
> 
> There's a bug in the setup script for tests 8. If you first run setup for test 7, the test 8 setup will set focus to the wrong item. If you refresh browser cache, the test 8 script will then work correctly and set focus to the first item.
> 
> To reproduce:
> 
> 1. Open the test plan in Chrome.
> 2. Open the test 7 test window.
> 3. Run the setup script for test 7.
> 4. Close the test 7 window .
> 5. Open the test 8 test window.
> 6. Run the test 8 setup.
> 
> Expected behavior: Focus is set on action 1.
> 
> Actual behavior: Focus is set on action 4.

Thank you, @mcking65, for reporting this. I haven’t been able to reproduce the issue so far, as both setup scripts seem to be working correctly and setting focus as expected. @jscholes, could you take a look when you have a chance?

**Review by mcking65 — APPROVED** [review]
@IsaDC 

Looks good. I'm merging based on our Tuesday conversation.

I did push one more fix ... the references.csv for the other action menu button with active descendant plan was somehow modified in these files. I corrected that so now all the mods are just with this one test plan.

**Pull request merged**
