### PR TITLE
chore: update package lock v2 and Node 16

### PR DESCRIPTION
**Pull request by nschonni**
[Preview Tests](https://deploy-preview-649--aria-at.netlify.app)

Bump the packlock to v2 and Node 16 running now that the node-git block is resolved. Ran `npm audit fix` in separate commits after the original automated conversion

### CODE REVIEW

**Comment by howard-e** [comment]
Thanks @nschonni! LGTM!

Just curious if there could be any adverse effects to this that we may need to be aware of @mzgoddard? I vaguely remember node version related issues popping up before around the build process. But I can't seem to track down the conversations related to those items to verify.

**Review by howard-e — APPROVED** [review]
Looks good @nschonni

> Just curious if there could be any adverse effects to this that we may need to be aware of? I vaguely remember node version related issues popping up around the build process. But I can't seem to track down the conversations related to those items to verify.

Nevermind @mzgoddard! Found the [issue](https://github.com/w3c/aria-at/pull/499) I was referring to. All looks good.

**Comment by nschonni** [comment]
Oh, I think lint-staged can now bump with this too, but that can always be done separately

**Comment by howard-e** [comment]
> Oh, I think lint-staged can now bump with this too, but that can always be done separately

Let's do that separately. Will land this.

**Pull request merged**
