### PR TITLE
Increase test page size

### PR DESCRIPTION
**Pull request by alflennik**
[Preview Tests](https://raw.githack.com/w3c/aria-at/increase-window-size/build/index.html)

Doubles the size of the test page window. No change was needed to make the window resizable since it is already resizable! Tested in Safari, Firefox and Chrome.

### CODE REVIEW

**Review by mzgoddard — CHANGES_REQUESTED** [review]
@alflennik Make the change in `test/resources/aria-at-test-window.mjs`. You made the change in `build/test/resources/aria-at-test-window.mjs` and then the github action clobbered it by copying `test/resources/aria-at-test-window.mjs` over it. Sorry for the confusion caused by the current action workflow.

**Review by mzgoddard — APPROVED** [review]
Nice!

**Comment by alflennik** [comment]
@mzgoddard no change is so small that it can't go awry, haha. I fixed it but now I'm seeing conflicts. Any tips on how to get this mergeable?

**Comment by mzgoddard** [comment]
@alflennik rebase onto master or merge master into your branch. At this time these conflicts are unavoidable when another PR is merged.

**Pull request merged**
